// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.WebApp.Data;

#nullable disable

namespace Restaurant.WebApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250427224300_AddContactMessagesTable")]
    partial class AddContactMessagesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Салати"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Месо"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Риба"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Паста"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Пица"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Суши"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Странични ястия"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Десерти"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Веган"
                        });
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHandled")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.DishReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("DishReviews");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "салата, авокадо",
                            ImageUrl = "https://i.imgur.com/ytAl6b7.jpg",
                            Name = "Салата с авокадо"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "салата, крутони, пиле",
                            ImageUrl = "https://i.imgur.com/46hWRKm.jpg",
                            Name = "Салата цезър"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "салата, риба тон",
                            ImageUrl = "https://i.imgur.com/nRqrS2Z.jpg",
                            Name = "Салата с риба тон"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "салата, лук, домати, краставица",
                            ImageUrl = "https://i.imgur.com/tGkD6Mz.jpg",
                            Name = "Гръцка салата"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "свинско месо с зеленчуци",
                            ImageUrl = "https://i.imgur.com/Mud7P5Z.jpg",
                            Name = "Свинско"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Телешко месо с картофи",
                            ImageUrl = "https://i.imgur.com/HeE8bQ5.jpg",
                            Name = "Телешко"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "кюфтета с картофи и зеленчуци",
                            ImageUrl = "https://i.imgur.com/eZEPgd8.jpg",
                            Name = "Кюфтета"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "пилешко месо, зеленчуци",
                            ImageUrl = "https://i.imgur.com/4HNR1ZY.jpg",
                            Name = "Пилешко месо"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Карбонара",
                            ImageUrl = "https://i.imgur.com/n4TbgT7.jpg",
                            Name = "Паста Карбонара"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Болонезе",
                            ImageUrl = "https://i.imgur.com/ZG42J7n.jpg",
                            Name = "Паста Болонезе"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "морски дарове с паста",
                            ImageUrl = "https://i.imgur.com/ea3XILH.jpg",
                            Name = "Паста с морски дарове"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Description = "кайма, кашкавал, босилек",
                            ImageUrl = "https://i.imgur.com/tWo1D41.jpg",
                            Name = "Лазаня"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "моцарела, доматен сос",
                            ImageUrl = "https://i.imgur.com/mabeII0.jpg",
                            Name = "Пица с моцарела"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "кюфтета, доматен сос, кашкавал",
                            ImageUrl = "https://i.imgur.com/mZItQiX.jpg",
                            Name = "Пица с кюфтета"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "сирена от различен вид",
                            ImageUrl = "https://i.imgur.com/91ey2lO.jpg",
                            Name = "Пица четири сирена"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Description = "салам, чери домати, босиляк",
                            ImageUrl = "https://i.imgur.com/mQ8m6YF.jpg",
                            Name = "Пица салами"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "сьомга на грил",
                            ImageUrl = "https://i.imgur.com/Iw86J6D.jpg",
                            Name = "Сьомга"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "с резънчета лимон и салата",
                            ImageUrl = "https://i.imgur.com/uWiso3I.jpg",
                            Name = "Риба на скара"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Description = "порция изчистени скариди",
                            ImageUrl = "https://i.imgur.com/maOOr2c.jpg",
                            Name = "Скариди"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "пържена риба с картофено пюре",
                            ImageUrl = "https://i.imgur.com/H35uMie.jpg",
                            Name = "Пържена риба"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Description = "Суши стил футомаки с рак",
                            ImageUrl = "https://i.imgur.com/I3HdRmg.png",
                            Name = "Футомаки Рак"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            Description = "Суши стил нигири със сьомга",
                            ImageUrl = "https://i.imgur.com/9PELxEu.png",
                            Name = "Нигири сьомга"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            Description = "Суши сет стил хосумаки",
                            ImageUrl = "https://i.imgur.com/BqDTtuo.png",
                            Name = "Хосумаки сет"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Description = "Суши пържен сет",
                            ImageUrl = "https://i.imgur.com/kGfrZXO.png",
                            Name = "Пържен сет"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            Description = "Прясно изпържени картофи с кашкавалена покривка",
                            ImageUrl = "https://i.imgur.com/LEzjncV.png",
                            Name = "Пържени картофи"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 7,
                            Description = "боб зелен соров",
                            ImageUrl = "https://i.imgur.com/35Rfcar.jpg",
                            Name = "Зелен боб"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 7,
                            Description = "изпечени прясни картофи",
                            ImageUrl = "https://i.imgur.com/afBYXEq.jpg",
                            Name = "Печени картофи"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 7,
                            Description = "Прясно изпечени зеленчуци",
                            ImageUrl = "https://i.imgur.com/wrkStpo.jpg",
                            Name = "Печени зеленчуци"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 8,
                            Description = "пърче чийскейк",
                            ImageUrl = "https://i.imgur.com/b98zxYM.jpg",
                            Name = "Чийскейк"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 8,
                            Description = "Домашно приготвено тирамису",
                            ImageUrl = "https://i.imgur.com/ucIJMQO.jpg",
                            Name = "Тирамису"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 8,
                            Description = "Палачинки с шоколад",
                            ImageUrl = "https://i.imgur.com/16gDj6l.jpg",
                            Name = "Палачинки"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 8,
                            Description = "Гофрети с кленов сироп",
                            ImageUrl = "https://i.imgur.com/nY9Cgqf.jpg",
                            Name = "Гофрети"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 9,
                            Description = "Тофу салата",
                            ImageUrl = "https://i.imgur.com/D2nrUPV.jpg",
                            Name = "Тофу"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 9,
                            Description = "дъмплинги по китайски",
                            ImageUrl = "https://i.imgur.com/mqmYr9T.jpg",
                            Name = "Дъмплинги"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 9,
                            Description = "2 яца по стил бъркани",
                            ImageUrl = "https://i.imgur.com/co7Mn3A.jpg",
                            Name = "Бъркани яйца с тостове"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 9,
                            Description = "със сос сладко кисел и вътрешност",
                            ImageUrl = "https://i.imgur.com/CbdHjAT.jpg",
                            Name = "Запържени ролца"
                        });
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChildrenNumber")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("PersonNumber")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Вътре в залата"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Отвън на терасата за пушачи"
                        });
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.SiteReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteReviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.CartItem", b =>
                {
                    b.HasOne("Restaurant.WebApp.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.DishReview", b =>
                {
                    b.HasOne("Restaurant.WebApp.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.Order", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("Restaurant.WebApp.Data.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.WebApp.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.Product", b =>
                {
                    b.HasOne("Restaurant.WebApp.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.Reservation", b =>
                {
                    b.HasOne("Restaurant.WebApp.Data.Entities.RoomType", "RoomType")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Restaurant.WebApp.Data.Entities.RoomType", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
